// model by eon/sketchfab https://sketchfab.com/3d-models/elven-ranger-statue-71aec2d9f7724ae09992435ce8ff7258
import { graphql } from 'gatsby'
import * as THREE from 'three'
import { render } from 'react-dom'
import React, { Suspense, useEffect, useRef, useMemo } from 'react'
import { Canvas, useThree, useFrame, extend } from 'react-three-fiber'
import { EffectComposer as EC, SSAO, SMAA } from 'react-postprocessing'
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer'
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass'
import { ShaderPass } from 'three/examples/jsm/postprocessing/ShaderPass'
import { FXAAShader } from 'three/examples/jsm/shaders/FXAAShader'
import { AdditiveBlendingShader, VolumetricLightShader } from './shaders'
import { useGLTF } from 'drei'
// import './styles.css'

import { Layout } from "../layout"

extend({ EffectComposer, RenderPass, ShaderPass })

const DEFAULT_LAYER = 0
const OCCLUSION_LAYER = 1

// Component auto-generated by GLTFJSX: https://github.com/react-spring/gltfjsx
function Elf({ layer = DEFAULT_LAYER }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cabin1.glb')
//   console.log(nodes);
//   console.log(materials);
//   const material = useMemo(() => {
//     if (layer === DEFAULT_LAYER) return new THREE.MeshStandardMaterial({ color: new THREE.Color('#2a2a2a'), roughness: 1, metalness: 0.9 })
//     else return new THREE.MeshBasicMaterial({ color: new THREE.Color('black') })
//   }, [layer])

  useFrame(() => (group.current.rotation.y += 0.004))

  return (
    <group ref={group}>
      <group rotation={[0, 0, 0]} position={[0, 0, 0]}>
        {/* <mesh geometry={nodes.Plane.geometry} material={materials.Bg} layers={layer} receiveShadow castShadow></mesh>   */}
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Floor} layers={layer} receiveShadow castShadow></mesh>
        <mesh geometry={nodes.Plane_2.geometry} material={materials.Wall} layers={layer} receiveShadow castShadow></mesh>
        <mesh geometry={nodes.Plane_3.geometry} material={materials.Sofa} layers={layer} receiveShadow castShadow></mesh>
        <mesh geometry={nodes.Plane_4.geometry} material={materials.Metal} layers={layer} receiveShadow castShadow></mesh>
        <mesh geometry={nodes.Plane_5.geometry} material={materials.Backlight} layers={layer} receiveShadow castShadow></mesh>
        <mesh geometry={nodes.Plane_6.geometry} material={materials.Black} layers={layer} receiveShadow castShadow></mesh>
        <mesh geometry={nodes.Plane_7.geometry} material={materials.TV} layers={layer} receiveShadow castShadow></mesh>
        <mesh geometry={nodes.Plane_8.geometry} material={materials.Wood} layers={layer} receiveShadow castShadow></mesh>
        <mesh geometry={nodes.Plane_9.geometry} material={materials.poster} layers={layer} receiveShadow castShadow></mesh>
        <mesh geometry={nodes.Plane_10.geometry} material={materials.Bg} layers={layer} receiveShadow castShadow></mesh>
      </group>
    </group>
  )
}

function Effects() {
  const { gl, scene, camera, size } = useThree()
  const occlusionRenderTarget = useMemo(() => new THREE.WebGLRenderTarget(), [])
  const occlusionComposer = useRef()
  const composer = useRef()

  useEffect(() => {
    occlusionComposer.current.setSize(size.width, size.height)
    composer.current.setSize(size.width, size.height)
  }, [size])

  useFrame(() => {
    camera.layers.set(OCCLUSION_LAYER)
    occlusionComposer.current.render()
    camera.layers.set(DEFAULT_LAYER)
    composer.current.render()
  }, 1)

  return (
    <>
      <mesh layers={OCCLUSION_LAYER} position={[0, 4.5, -10]}>
        <sphereBufferGeometry args={[5, 32, 32]} />
        <meshBasicMaterial />
      </mesh>
      <effectComposer ref={occlusionComposer} args={[gl, occlusionRenderTarget]} renderToScreen={false}>
        <renderPass attachArray="passes" args={[scene, camera]} />
        <shaderPass attachArray="passes" args={[VolumetricLightShader]} needsSwap={false} />
      </effectComposer>
      <effectComposer ref={composer} args={[gl]}>
        <renderPass attachArray="passes" args={[scene, camera]} />
        {/* <shaderPass attachArray="passes" args={[AdditiveBlendingShader]} uniforms-tAdd-value={occlusionRenderTarget.texture} /> */}
        <shaderPass attachArray="passes" args={[FXAAShader]} uniforms-resolution-value={[1 / size.width, 1 / size.height]} renderToScreen />
      </effectComposer>
    </>
  )
}

export default ({ data, location }) => {
    const { siteMetadata } = data.site
  return (
    <Layout location={location} title={siteMetadata.title} style={{ height: '100vh' }}>
    <Canvas shadowMap style={{ background: '#282c35' }} camera={{ position: [0, 20, 30], fov: 60 }} gl={{ antialias: false }}>
      <Suspense fallback={null}>
        <Elf />
        <Elf layer={OCCLUSION_LAYER} />
        <EC multisampling={0}>
            <SSAO
                intensity={40}
                luminanceInfluence={0.2}
                radius={8}
                scale={0.5}
                bias={0.5}
                distanceThreshold={0.5}
                distanceFalloff={0.03}
                rangeFalloff={0.001}
            />
            <SMAA />
        </EC>
      </Suspense>
      <Effects />
    </Canvas>
    </Layout>
  )
}


export const pageQuery = graphql`
  query {
    site {
      siteMetadata {
        title
        configs {
          countOfInitialPost
        }
      }
    }
    allMarkdownRemark(
      sort: { fields: [frontmatter___date], order: DESC }
      filter: { frontmatter: { category: { ne: null }, draft: { eq: false } } }
    ) {
      edges {
        node {
          excerpt(pruneLength: 200, truncate: true)
          fields {
            slug
          }
          frontmatter {
            date(formatString: "MMMM DD, YYYY")
            title
            category
            draft
          }
        }
      }
    }
  }
`